
GET http://localhost:5000/usuarios
Content-Type: application/json


{

}


###
POST http://localhost:5000/usuarios
Content-Type: application/json

{
  "nome": "Honey Black",
  "email": "honeyblackout@gmail.com",
  "senha": "melpreto",
  "curso": "Analise e Desenvolvimente de Sistemas",
  "disciplina": "",
  "periodo": "3°",
  "tipoUsuario": "aluno"
}

###
PUT http://localhost:5000/usuarios/67103f865e99546bc463039f
Content-Type: application/json


{
  "nome": "Messi Silva",
  "email": "fifa@email.com",
  "senha": "ladr",
  "curso": "Sistemas para Internet",
  "disciplina": "",
  "periodo": "3°",
  "tipoUsuario": "aluno"
}
###
DELETE http://localhost:5000/usuarios/671c119bd73550ff1204914f

###
POST http://localhost:5000/usuarios/login
Content-Type: application/json

{
  "email": "lipe@email.com",
  "senha": "lipe"
}